version: '3'
services:
  docker-in-docker:
    image: docker:dind
    privileged: true
    expose:
      - 2375
      - 2376
      
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins

    ports:
      - "80:8080"
    volumes:
      - ./home:/var/jenkins_home:w
    restart: unless-stopped
    links:
      - docker-in-docker
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
